### PR TITLE
no changes made...

### PR DESCRIPTION
**Pull request by vanshg395**

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
@vanshg395 
I didn't get it, is it done with any purpose? 
Or you getting your hand dirty with creating your first PR??

**Comment by vinitshahdeo** [comment]
@vanshg395 

> I didn't get this. Is it done for any purpose or just getting your hand dirty with creating your first PR?

If so, we'll decline the PR.

**Comment by vanshg395** [comment]
This is not my first pull request. There was some missing files in repo
which were not uploaded earlier due to some problem. So i asked Angad
Bhaiya, after seeing the error, he said to make a pull request and then
push the missing files.

**Comment by L04DB4L4NC3R** [comment]
@vanshg395 nothing was added or deleted here

**Comment by vanshg395** [comment]
feature for sending sms to multiple contacts is added

**Pull request closed without merging**
